[[tests]]
input = '''
4 # # 
4 # # 
'''
output = '''
4
4
iguais
'''

[[tests]]
input = '''
1 # 0 # # 
1 # 1 # # 
'''
output = '''
╭───#
1
╰───0
╭───#
1
╰───1
menor
'''

[[tests]]
input = '''
1 # 2 # # 
1 # 1 # # 
'''
output = '''
╭───#
1
╰───2
╭───#
1
╰───1
maior
'''

[[tests]]
input = '''
1 2 # # # 
1 # 2 # # 
'''
output = '''
╭───2
1
╰───#
╭───#
1
╰───2
maior
'''

[[tests]]
input = '''
1 # 2 # # 
1 2 # # # 
'''
output = '''
╭───#
1
╰───2
╭───2
1
╰───#
menor
'''

[[tests]]
input = '''
4 # 8 2 # # # 
4 # 8 2 # # # 
'''
output = '''
╭───#
4
│   ╭───2
╰───8
    ╰───#
╭───#
4
│   ╭───2
╰───8
    ╰───#
iguais
'''

[[tests]]
input = '''
4 # 8 2 # # # 
4 8 2 # # # #
'''
output = '''
╭───#
4
│   ╭───2
╰───8
    ╰───#
    ╭───2
╭───8
│   ╰───#
4
╰───#
menor
'''

[[tests]]
input = '''
0 9 4 # # # 5 # # 
0 8 4 # # # 5 # # 
'''
output = '''
    ╭───4
╭───9
│   ╰───#
0
╰───5
    ╭───4
╭───8
│   ╰───#
0
╰───5
maior
'''
