test:
	g++ -Wall main.cpp solver.cpp -o solver.out
	tk run solver.out Readme.md
	rm -f solver.out

student:
	g++ -Wall main.cpp student.cpp -o solver.out
	tk run solver.out Readme.md
	rm -f solver.out

