[[tests]]
input = '''
4 # # 
'''
output = '''
Arvore:
4
Soma: 4, Minimo: 4
'''

[[tests]]
input = '''
1 # 0 # # 
'''
output = '''
Arvore:
╭───#
1
╰───0
Soma: 1, Minimo: 0
'''

[[tests]]
input = '''
4 # 8 2 # # # 
'''
output = '''
Arvore:
╭───#
4
│   ╭───2
╰───8
    ╰───#
Soma: 14, Minimo: 2
'''

[[tests]]
input = '''
0 9 4 # # # 5 # # 
'''
output = '''
Arvore:
    ╭───4
╭───9
│   ╰───#
0
╰───5
Soma: 18, Minimo: 0
'''

[[tests]]
input = '''
0 4 # # 2 0 # # -3 # # 
'''
output = '''
Arvore:
╭───4
0
│   ╭───0
╰───2
    ╰───-3
Soma: 3, Minimo: -3
'''

[[tests]]
input = '''
2 0 5 # # # 3 # 7 # -9 # # 
'''
output = '''
Arvore:
    ╭───5
╭───0
│   ╰───#
2
│   ╭───#
╰───3
    │   ╭───#
    ╰───7
        ╰───-9
Soma: 8, Minimo: -9
'''

[[tests]]
input = '''
1 8 7 # # 4 # 6 # # 5 0 # # 9 # 3 2 # # # 
'''
output = '''
Arvore:
    ╭───7
╭───8
│   │   ╭───#
│   ╰───4
│       ╰───6
1
│   ╭───0
╰───5
    │   ╭───#
    ╰───9
        │   ╭───2
        ╰───3
            ╰───#
Soma: 45, Minimo: 0
'''
