[[tests]]
input = '''
1
'''
output = '''
1
'''

[[tests]]
input = '''
2
'''
output = '''
0
'''

[[tests]]
input = '''
3
'''
output = '''
0
'''

[[tests]]
input = '''
4
'''
output = '''
2
'''

[[tests]]
input = '''
5
'''
output = '''
10
'''

[[tests]]
input = '''
6
'''
output = '''
4
'''

[[tests]]
input = '''
7
'''
output = '''
40
'''

[[tests]]
input = '''
8
'''
output = '''
92
'''

[[tests]]
input = '''
9
'''
output = '''
352
'''

[[tests]]
input = '''
10
'''
output = '''
724
'''

[[tests]]
input = '''
11
'''
output = '''
2680
'''

[[tests]]
input = '''
12
'''
output = '''
14200
'''
