[[tests]]
input = '''
3 20
'''
output = '''
17.50
'''

[[tests]]
input = '''
6 20
'''
output = '''
19.69
'''

[[tests]]
input = '''
6 10
'''
output = '''
9.84
'''

[[tests]]
input = '''
5 20
'''
output = '''
19.38
'''
