[[tests]]
input = '''
1
'''
output = '''
[2]
'''

[[tests]]
input = '''
2
'''
output = '''
[2, 3]
'''

[[tests]]
input = '''
3
'''
output = '''
[2, 3, 5]
'''

[[tests]]
input = '''
7
'''
output = '''
[2, 3, 5, 7, 11, 13, 17]
'''
