[[tests]]
input = '''
5
'''
output = '''
0 1
1 0
2 1
'''

[[tests]]
input = '''
100
'''
output = '''
0 1
1 1
3 0
6 0
12 1
25 0
50 0
'''

[[tests]]
input = '''
101
'''
output = '''
0 1
1 1
3 0
6 0
12 1
25 0
50 1
'''

[[tests]]
input = '''
150
'''
output = '''
0 1
1 0
2 0
4 1
9 0
18 1
37 1
75 0
'''
