test:
	g++ -Wall solver.cpp lib.cpp main.cpp -o solver.out
	tk run solver.out Readme.md
	rm -f solver.out

student:
	g++ -Wall student.cpp lib.cpp main.cpp -o solver.out
	tk run solver.out Readme.md
	rm -f solver.out