[[tests]]
input = '''
4 # # 
'''
output = '''
4
'''

[[tests]]
input = '''
1 # 0 # # 
'''
output = '''
╭───#
1
╰───0
'''

[[tests]]
input = '''
4 # 8 2 # # # 
'''
output = '''
╭───#
4
│   ╭───2
╰───8
    ╰───#
'''

[[tests]]
input = '''
0 9 4 # # # 5 # # 
'''
output = '''
    ╭───4
╭───9
│   ╰───#
0
╰───5
'''

[[tests]]
input = '''
0 4 # # 2 0 # # 3 # # 
'''
output = '''
╭───4
0
│   ╭───0
╰───2
    ╰───3
'''

[[tests]]
input = '''
2 0 0 # # # 3 # 7 # 9 # # 
'''
output = '''
    ╭───0
╭───0
│   ╰───#
2
│   ╭───#
╰───3
    │   ╭───#
    ╰───7
        ╰───9
'''

[[tests]]
input = '''
1 8 7 # # 4 # 6 # # 5 0 # # 9 # 3 2 # # # 
'''
output = '''
    ╭───7
╭───8
│   │   ╭───#
│   ╰───4
│       ╰───6
1
│   ╭───0
╰───5
    │   ╭───#
    ╰───9
        │   ╭───2
        ╰───3
            ╰───#
'''
