[[tests]]
input = '''
4 # # 
'''
output = '''
original:
4
clone:
4
'''

[[tests]]
input = '''
1 # 0 # # 
'''
output = '''
original:
╭───#
1
╰───0
clone:
╭───#
1
╰───0
'''

[[tests]]
input = '''
4 # 8 2 # # # 
'''
output = '''
original:
╭───#
4
│   ╭───2
╰───8
    ╰───#
clone:
╭───#
4
│   ╭───2
╰───8
    ╰───#
'''

[[tests]]
input = '''
0 9 4 # # # 5 # # 
'''
output = '''
original:
    ╭───4
╭───9
│   ╰───#
0
╰───5
clone:
    ╭───4
╭───9
│   ╰───#
0
╰───5
'''

[[tests]]
input = '''
0 4 # # 2 0 # # 3 # # 
'''
output = '''
original:
╭───4
0
│   ╭───0
╰───2
    ╰───3
clone:
╭───4
0
│   ╭───0
╰───2
    ╰───3
'''

[[tests]]
input = '''
2 0 0 # # # 3 # 7 # 9 # # 
'''
output = '''
original:
    ╭───0
╭───0
│   ╰───#
2
│   ╭───#
╰───3
    │   ╭───#
    ╰───7
        ╰───9
clone:
    ╭───0
╭───0
│   ╰───#
2
│   ╭───#
╰───3
    │   ╭───#
    ╰───7
        ╰───9
'''
